---
title: "Assignment_1"
output:
  word_document: default
  html_document: default
date: "2022-09-10"
---
data source: https://www.openintro.org/data/index.php?data=fastfood
```{r}
data<-read.csv("Nutritional_Information.csv")
```

#Q.1 Print out descriptive statistics for a selection of quantitative and qualitative variables
```{r}
print(summary(data$calories))
```
```{r}
print(sd(data$calories, na.rm=FALSE))
```
```{r}
print(range(data$calories, na.rm=FALSE))
```
```{r}
print(summary(data$restaurant))
```
#Q.2 Transform at least one variable. 
```{r}
library(dplyr)
filter(data, restaurant=="Subway", calories<300, trans_fat==0, sodium<1000)
```
#Q.3 Plot at least one quantitative variable and one scatterplot
```{r}
hist(data$calories, main="Histogram of Calories in Fast Food Items", xlab="Calories")
```

```{r}
plot(data$total_fat,data$calories, main="Scatterplot of Calories and Total Fat in Fast Food Items", xlab="Total Fat", ylab="Calories")
```











